[package]
name = "funqy"
version = "0.1.0"

[dependencies]
rand = "^0.4.2"
num = "^0.1.42"
nom = "^3.2"
ndarray = "0.11"
# ndarray-linalg = "0.9"
ndarray-linalg = { version = "0.9", features = ["openblas"] }